deploy/upstart/dhtdump-instance.conf, deploy/upstart/dhtnode-instance.conf, src/dhtnode/dhtdump/main.d, src/dhtnode/main.d, src/dhtnode/request/ListenRequest.d
The commits in this PR were made against the old v1.9.x branch in the private dhtnode repo. Bringing them into v1.10.x here.
Notes:
* v1.9.9: Commit 44400b7d1e67130433bed737e80e03d49bd6135a (in the private repo) is included in the PR but reverted. The bug that it was investigating has since been fixed. (Requires a dhtproto submodule update. See #32.)
* v1.9.10: Commit fd1c23f9359d7e72d91b3acc0a4cbaa49525896e (in the private repo) was left out. It updated to the latest patch releases of submodules used by v1.9.x. This will be replaced by #32.
=> Cherries from v1.9.7 - v1.9.10

README.rst, deploy/systemd/dht@.service, deploy/systemd/dhtdump@.service, pkg/dhtnode-common.pkg
This commit removes upstart scripts and changes the package to use
systemd init system instead of upstart. Note that the packages
installed from this point will not include any support for upstart.
Fixes #3
=> Add systemd support for dhtnode and dhtdump

src/dhtnode/node/RequestHandlers.d
Blocked on [swarm v4.4.0](https://github.com/sociomantic-tsunami/swarm/milestone/25).
=> Don't log timing stats for long-lived neo requests

.travis.yml
Since stages don't share the artefacts, this builds the package
that will be uploaded in the pkg stage.
=> Build dhtnode package before trying to upload it

.travis.yml
Using the default cachalot v3 images version, so there should be no
changes in practice.
=> travis: Use explicit DMD versions

.travis.yml
Using Travis cache feature we can actually pass the generated package in
the build stage to the upload stage, so we make sure we upload the exact
same package we just tested.
=> travis: Pass the generated package to the upload stage

pkg/after_dhtnode_install.sh
dhtnode install script relies on /srv/dhtnode/dhtnode-* structure is setup.
If it doesn't exist, instead of silent exit it should printout the error
message. Also remove outdated comment.
=> Add the error message in package install script and remove outdated comment

.travis.yml
Since the docker service doesn't persist between stages,
we need to rebuild the docker image before pushing tags.
=> Add beaver dlang install to build package stage

src/dhtnode/request/ListenRequest.d, src/dhtnode/storage/StorageEngine.d
This saves an internal conversion from string to hash.
=> Pass keys to listener triggers as hash_t, instead of char[]

src/dhtnode/storage/StorageEngine.d
Since #37, the storage engine stores keys internally as integers (hash_t),
rather than strings. The existing hash_t-accepting storage methods convert
their key into a string, which is passed to the string-accepting method and
then converted back to a hash. This commit factors out that double
conversion. The hash_t-accepting methods are now the primary methods.
Fixes #92.
=> Adapt storage engine methods to not convert hashes

.travis.yml
For artifact caching to work, env lines muyst match exactly as strings
between stages
=> Match env lines exactly

deploy/logrotate/dhtdump-logs, deploy/logrotate/dhtnode-logs
Instead of relying on the fixed binary name, which has problems
when overriding systemd services, this relies on service name
which is fixed.
=> Use `systemctl reload` to reload config files

docker/Dockerfile.dhtnode, docker/install.sh
Removes the need to add Sociomantic apt server manually
=> Switch to runtimebase image for Dockerfile

docker/Dockerfile.dhtnode
Most important impact is that generated runtime images will include
dumb-init as the entry point.
=> Switch to v7 cachalot images

deploy/logrotate/dhtdump-logs, deploy/logrotate/dhtnode-logs
`notifempty` causes rotated files (e.g. `some.log.1`) to not be further
rotated.
Fixes #164.
=> Replace `notifemtpy` -> `ifempty` in logrotate config

pkg/after_dhtnode_install.sh
If the package postinstall script can't add user and a group (usually
because the user already exist), don't exit the after install script.
Instead ignore the error and check if the user and the group are setup
correctly.
=> Do not fail if can't create user and group

src/dhtredist/RedistDhtClient.d
`HashRange` is not a public import in `dhtproto.client.legacy.DhtConst`, so it is only accessible thanks to a compiler bug which makes selective imports implicitly public.
This bug has been fixed in more recent D2 compiler versions, so we need to import from swarm to guarantee access to the `HashRange` symbol.
=> Import HashRange directly from swarm in RedistDhtClient

src/dhtnode/main.d
This is not actually used in the codebase any more, and importing it will block upgrades to ocean v5.x.x, from which it has been dropped.
This should remove one of the blockers to https://github.com/sociomantic-tsunami/dhtnode/pull/226.
=> Drop import of deprecated and unused OutOfMemoryException

src/dhtnode/request/RedistributeRequest.d, src/dhtnode/storage/DumpManager.d, src/dhtnode/storage/StorageChannels.d
Since the batch size is now configured in the nodes config file this change also makes it possible
(and necessary) to change two private methods of the DumpManager module to non static.
=> Remove usage of global recordSizeLimit constant

integrationtest/dhttest/etc/config.ini, neotest/main.d, src/dhtnode/config/PerformanceConfig.d, src/dhtnode/main.d, src/dhtnode/node/DhtNode.d
The `TCP_NODELAY` is always on, independent of the configuration flag. Therefore the option is removed from the configuration. Also the method that enables `TCP_NODELAY` in swarm is deprecated and removed from the latest major release.
=> Remove TCP no_delay option

Build.mak, src/dhtnode/main.d
The `stomping_prevention_counter` global is only accessible when using `dmd-transitional`.  If we want to build with vanilla DMD or any other compiler, we cannot use this symbol, so this patch replaces the original `D_Version2` version constraint with one specific to stomping prevention stats.
By default this will be enabled in `Build.mak`, but it can be overridden by using the `DISABLE_STOMPING_STATS` environment variable.  This should ensure that current behaviour persists by default, but build for vanilla DMD (or other compilers) can be added which disable the feature.
=> Add a StompingPreventionStats version constraint
